aiida shell version and __DIR__ replacement
H2020-OpenModel/ExecFlow pull request #19
Opened 2023-11-12 18:44 UTC by louisponet

2023-11-15 16:48 UTC, francescalb commented on tests/samples/exec_wrapper.yaml
I am trying to run the test locally and I get errors, which are difficult to debug. 

When tryin to use the script run_workflow.py
`
#!/usr/bin/env python
"""Script to run AiiDA declarative chain"""
import os
import sys
from pathlib import Path

import aiida
import dlite
from aiida import engine, orm
from execflow.workchains.declarative_chain import DeclarativeChain

aiida.load_profile()
if __name__ == "__main__":
    workflow = sys.argv[1]  # pylint: disable=invalid-name
    all_spec = {
        "workchain_specification": orm.SinglefileData(os.path.abspath(workflow))
    }

    engine.run(DeclarativeChain, **all_spec)
`

It fails with the following output on that step in the workchain in AiiDA.

Property     Value
-----------  -----------------------------------------------------------------
type         ExecWrapper
state        Excepted <ValueError: path `__DIR__/bc.template` is not absolute>
pk           6778
uuid         5ec13315-46c7-46fc-9281-b71aa7faea5b
label
description
ctime        2023-11-15 17:42:34.263134+01:00
mtime        2023-11-15 17:42:34.517599+01:00

Inputs       PK  Type
---------  ----  ------
arguments  6777  List
command    6776  Str

Caller      PK  Type
--------  ----  ----------------
CALL      6775  DeclarativeChain

Log messages
---------------------------------------------
There are 1 log messages for this calculation
Run 'verdi process report 6778' to see them

2023-11-15 16:58 UTC, francescalb requested changes
In addition to the comment onthe exec_wrapper.yaml run here, this change ot execflow creates issues for the examples used in D5.5.

When running

I get the following problem: 
```
ValueError: Error occurred validating port 'inputs': input `metadata.options.resources` is not valid for the `DirectScheduler` scheduler: At least two among `num_machines`, `num_mpiprocs_per_machine` or `tot_num_mpiprocs` must be specified.
```

I do not see that these are added here, but apparently this is needed in some manner. 

Can you also try to run the example: 
 workflow_complete_mockexecutables.yml in Public/OntoTrans2ndWorkshop (This is the Public repo here in OpenModel on github)

2023-11-16 14:39 UTC, louisponet commented on tests/samples/exec_wrapper.yaml
To use __DIR__ you need to pass in the path to the file as an aiida.orm.Str. Apparently since the most recent versions of aiida, SinglefileData doesn't store the full path anymore ...

2023-11-16 14:41 UTC, louisponet commented
It's very weird, I  think this is due to somehow aiida shell but I can't really think why... I don't understand why it works for the test but not for other things. Also the error messages are really super unuseful in this case ... AiiDA never ceases to amaze

2023-11-16 18:08 UTC, hothello commented
I can confirm that the three workflows in D5.5 work after the last commit. Check the branch `tbox_tripper` in the repository [H2020-OpenModel/Public](https://github.com/H2020-OpenModel/Public/tree/tbox_tripper/Deliverable5.5/demo1).
The workflow for SS1, based on Quantum Espresso, also works with this version of ExecFlow. Here is the status of my virtual environment:
```
aiida-core              2.4.0
aiida-pseudo            1.1.0
aiida-quantumespresso   4.4.0
aiida-shell             0.6.0
DLite-Python            0.4.5
execflow                0.1.0
execflowdemo            0.1.0
ExecFlowDemoAiiDAShell  0.0.1
executing               1.2.0
ontoflow                0.0.1
oteapi-core             0.4.4
oteapi-dlite            0.1.6
Pint                    0.16.1
tripper                 0.2.12
```

2023-12-05 18:08 UTC, francescalb commented
I also get this to work when I add what Otello has done in his usecase:
      shelljob:
        metadata:
          options:
            resources:
              num_machines: 1
              num_mpiprocs_per_machine: 1

Can we set num_machines and num_mpiprocs_per_machine  both to 1 as default?

2023-12-18 08:53 UTC, francescalb commented
> I also get this to work when I add what Otello has done in his usecase: shelljob: metadata: options: resources: num_machines: 1 num_mpiprocs_per_machine: 1
> 
> Can we set num_machines and num_mpiprocs_per_machine both to 1 as default?

@louisponet  I think this PR is OK, but isn't it better to add default values for numprocs and nummachines? Otherwise we break back-compatibiility.

2023-12-20 08:54 UTC, louisponet commented
Done!

2024-03-04 12:49 UTC, francescalb commented
@louisponet  Since this development was merged in the previous PR can we close this?

2024-06-26 13:47 UTC, francescalb commented
Has already been merged.

2024-06-26 13:47 UTC, closed without merging